baseURL = "https://gildedernacht.ch/"
DefaultContentLanguage = "de"
theme = "gilde-der-nacht"
themesDir = "../../themes"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    title = "Luzerner Rollenspieltage"
    weight = 1
    languageName = "Deutsch"
    [languages.de.params]
      footer = "Die Luzerner Rollenspieltage werden organisiert durch den Spielverein, Gilde der Nacht"
  [languages.en]
    title = "Luzerner Rollenspieltage"
    weight = 2
    languageName = "English"
    [languages.en.params]
      footer = "The Luzerner Rollenspieltage are organised by the game society, Gilde der Nacht."
