baseURL = "https://gildedernacht.ch/"
DefaultContentLanguage = "de"
theme = "gilde-der-nacht"
themesDir = "../../themes"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    title = "Gilde der Nacht"
    weight = 1
    languageName = "Deutsch"
  [languages.en]
    title = "Gilde der Nacht"
    weight = 2
    languageName = "English"