baseURL = "https://gildedernacht.ch/"
DefaultContentLanguage = "de"
theme = "gilde-der-nacht"
themesDir = "../../themes"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    title = "Gilde der Nacht"
    weight = 1
    languageName = "Deutsch"
    [languages.de.params]
      footer = "Footertext TODO"
      source = "Quelle"
  [languages.en]
    title = "Gilde der Nacht"
    weight = 2
    languageName = "English"
    [languages.en.params]
      footer = "Footertext Englisch TODO."
      source = "Source"